name: dchisel
description: A simple dart web framework for create REST API
version: 1.1.0+4
repository: https://github.com/alalawy/DChisel

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  postgres: ^2.4.2
  shelf_plus: ^1.5.0
  
  mysql_client: ^0.0.27
  process_run: ^0.12.2+1
  shelf_hotreload: ^1.3.0
  shelf_static: ^1.1.1
  dart_jsonwebtoken: ^2.4.0
  crypto: ^3.0.1
  shelf_cors_headers: ^0.1.2
  shelf_virtual_directory: ^3.0.0

executables:
  dchisel: dchisel

platforms:
  windows:
  linux:
  macos:

#dev_dependencies:
  #pedantic: ^1.10.0
